[package]
name = "eratosthenes-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.5.1"
actix-web-actors = "4.3.0"
futures-util = "0.3.30"
tokio = { version = "1.36.0", features = ["full"] }
tokio-stream = "0.1.14"
warp = "0.3.6"
