{
 "title": "Eratosthenes",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PRS across all HTTP endpoints",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task:http_request",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Processing time across all HTTP endpoints (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "processing_time_ms",
       "id": "1",
       "settings": {
        "percents": [
         "50",
         "95",
         "99"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "task:http_request",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "HTTP endpoints with highest average processing time (ms)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "endpoint",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "processing_time_ms",
       "id": "1",
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "task:http_request",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "HTTP endpoints that get called most often",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "endpoint",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task:http_request",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Most active IPs (HTTP requests)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "client_ip",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task:http_request",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "WS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "PRS across all WS message types",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task:client_sent_ws_message",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Processing time across all WS message types (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "processing_time_ms",
       "id": "1",
       "settings": {
        "percents": [
         "50",
         "95",
         "99"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "task:client_sent_ws_message",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "WS messages with highest average processing time (ms)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "message_type",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "processing_time_ms",
       "id": "1",
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "task:client_sent_ws_message",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "WS messages that get sent most often",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "message_type",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task:client_sent_ws_message",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Most active IPs (WS messages)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "client_ip",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task:client_sent_ws_message",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total sockets count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task:sockets_count",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}